# Generated by Django 5.2.17 on 2026-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50, unique=True)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
