# Generated by Django 5.2.17 on 2026-09-09 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.PositiveIntegerField()),
                ('tipo_licencia', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id_admins',
            field=models.ManyToManyField(blank=True, to='ubicar.administrador'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id_conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.conductor'),
        ),
    ]
