# Generated by Django 6.1 on 2026-09-10 23:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0003_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_posicion', models.IntegerField(primary_key=True, serialize=False)),
                ('posicion_x', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('posicion_y', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hora', models.DateTimeField()),
                ('id_viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.viaje')),
            ],
        ),
    ]
