# Generated by Django 6.1 on 2026-09-10 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0004_viaje_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='id_conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.conductor'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_patente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.vehiculo'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.ruta'),
        ),
    ]
