# Generated by Django 5.2.17 on 2026-09-11 02:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0005_viaje_id_conductor_viaje_id_patente_viaje_id_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('idGasto', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprobante', models.CharField(max_length=250)),
                ('fechaYHora', models.DateTimeField()),
                ('estado', models.CharField(max_length=15)),
                ('kmRegistrado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicar.administrador')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicar.viaje')),
            ],
        ),
    ]
