# Generated by Django 6.1 on 2026-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0006_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='fechaYHora',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='kmRegistrado',
            new_name='km_registrado',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='idGasto',
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_gasto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_admin',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='id_conductor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='id_posicion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='posicion_x',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='posicion_y',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='id_ruta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_viaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
