# Generated by Django 6.1 on 2026-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicar', '0007_rename_fechayhora_gasto_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
